version: '3'
services:
  user-service-app:
    container_name: user-service-app
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        - PORT=8000
    restart: always
    ports:
      - 3000:8000
    environment:
      - DATABASE_URL=$DATABASE_URL
    # env_file:
    #   - .env